# Generated by Django 2.2.1 on 2020-02-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('fone', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
